Create a NumPy array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [2]:
import numpy as np
arr=np.array(2)
print(arr)

2


1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [4]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [6]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[22,33,44,55,66],[34,56,76,89,0]]])
print(arr)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[22 33 44 55 66]
  [34 56 76 89  0]]]


In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


NumPy Array Indexing

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[4])


5


Get third and fourth elements from the following array and add them.

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3]* arr[4])

20


Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [12]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[3,5,7,2],[2,6,7,3]])
print(arr[0,3],arr[1,4])

4 10


Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [14]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])


6


NumPy Array Slicing

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]


STEP
Use the step value to determine the step of the slicing:

In [19]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:8:2])

[2 4 6 8]


Slicing 2-D Arrays

In [21]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:5])

[ 7  8  9 10]


From both elements, return index 2

In [22]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

In [23]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4,])

[[2 3 4]
 [7 8 9]]


From both elements, slice index 1 to index 4 (not included), this will return a 3-D array

In [1]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[3,5,2,6,8],[34,54,36,22,11]]])
print(arr[0:2,0:2,1:4])


[[[ 2  3  4]
  [ 7  8  9]]

 [[ 5  2  6]
  [54 36 22]]]


NumPy Data Types

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [4]:
import numpy as np
arr=np.array(['aewff','bewfa','cwefwe','dftger','ewerfg'])
print(arr.dtype)

<U6


Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

Change data type from float to integer by using 'i' as parameter value:

In [5]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

COPY:

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


VIEW:

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


NumPy Array Reshaping

Reshape From 1-D to 2-D

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

Iterate on the elements of the following 1-D array:

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


Iterating 2-D Arrays
In a 2-D array it will go through all the rows.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

for x in arr:
    for y in x:
        print(y)


[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [3]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

for x in arr:
    for y in x:
        print(y)

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [4]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [2]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


Iterating With Different Step Size
We can use filtering and followed by iteration.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


NumPy Joining Array

Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


Join two 2-D arrays along rows (axis=1):

In [5]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
